spring:
  application:
    name: proposta-fin-app-ms-notificacao
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
rabbitmq:
  queue:
    proposta:
      pendente: proposta-pendente.ms-notificacao
aws:
  sns:
    access-key: ${AWS_SNS_ACCESS_KEY}
    secret-key: ${AWS_SNS_SECRET_KEY}
#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0